apiVersion: v1
baseDomain: ${base-domain}
compute:
- hyperthreading: Enabled
  name: worker
  replicas: 0
controlPlane:
  hyperthreading: Enabled
  name: master
  replicas: ${masters_count}
metadata:
  name: ${cluster-name}
platform:
  none: {}
pullSecret: '${pull-secret}'
sshKey: '${ssh-key}'
